queue_rules:
  - name: default
    conditions:
      - check-success=build

pull_request_rules:
  - name: merge using the merge queue
    conditions:
      - base=main
      - check-success=build
    actions:
      queue:
        name: default